POST http://localhost:5152/post
Content-Type: application/json

"msg1 from Inna"

###

GET http://localhost:5152/get

###
POST http://localhost:5248/post
Content-Type: application/json

"msg3"

###
GET http://localhost:5248/get